#!/usr/bin/env bash
# Caveat: any variable inside curly braces will be interpolated by terraform!
#
# bootstrap to make installing EPEL repo easy
function epel_bootstrap() {
    cat <<EOM > /etc/yum.repos.d/epel-bootstrap.repo
[epel]
name=Bootstrap EPEL
mirrorlist=http://mirrors.fedoraproject.org/mirrorlist?repo=epel-\$releasever&arch=\$basearch
failovermethod=priority
enabled=0
gpgcheck=0
EOM
    yum --enablerepo=epel -y install epel-release
    rm -f /etc/yum.repos.d/epel-bootstrap.repo
}

## Test for OS, install dependencies, and determine SSH_USER
if [ -f /etc/centos-release ]; then
    SSH_USER="centos"
    epel_bootstrap
    yum update -y
elif [ -f /etc/redhat-release ]; then
    SSH_USER="ec2-user"
    epel_bootstrap
    yum update -y
elif [ -f /etc/debian_version ]; then
    SSH_USER="ubuntu"
    apt-get update -y
fi
